# Generated by Django 3.2.12 on 2022-04-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='url',
            field=models.URLField(),
        ),
    ]
